spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2

  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.letscode.account.JMS.deserializer.AddRequestDeserializer
      group-id: group_id

auto:
  create:
    topics:
      enable: true

server:
  port: ${port:8082}

kafka:
  topic:
    name: eighteleven.samples.topic
